name: GitGuardian scan

on: [push, pull_request]

jobs:
  scanning:
    name: GitGuardian scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install ggshield
        run: pip install ggshield

      - name: Full repo secret scan
        env:
          GITGUARDIAN_API_KEY: ${{ secrets.API_KEY_Guardian }}
        run: ggshield secret scan repo . --yes --all-secrets
